# Generated by Django 3.0.5 on 2020-04-30 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
